# Generated by Django 4.0.5 on 2022-06-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_cursoApp', '0003_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.AlterField(
            model_name='curso',
            name='info',
            field=models.CharField(max_length=100),
        ),
    ]
