# Generated by Django 4.0.5 on 2022-06-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_cursoApp', '0004_delete_contacto_alter_curso_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
